spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://127.0.0.1:5432/dataroom?currentSchema=public&rewriteBatchedStatements=true
    username: root
    password: 123456